/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cisa_impresores;

import cisa_impresores.swing.Comu;
import cisa_impresores.swing.LC;
import Exceptions.CisaExceptions;
import HPComu.HPComu;
import ImpresoraJordi.BrotherJordi;
import cisa_impresores.swing.BroJordi;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author linusdufol
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() throws IOException, MalformedURLException, CisaExceptions {
        HPComu hpcomu = new HPComu();
        hpcomu.HPComu();
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hpcomu = new javax.swing.JButton();
        BroJordi = new javax.swing.JButton();
        BroLC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IMPRESSORES OFICINES CISA");

        hpcomu.setText("HP COMUNA");
        hpcomu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpcomuActionPerformed(evt);
            }
        });

        BroJordi.setText("BROTHER JORDI");
        BroJordi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroJordiActionPerformed(evt);
            }
        });

        BroLC.setText("BROTHER LAURA & CRISTINA");
        BroLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroLCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(BroLC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(hpcomu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(BroJordi)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(hpcomu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BroJordi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BroLC)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hpcomuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpcomuActionPerformed
        Comu f = null;
        try {
            f = new Comu(this, rootPaneCheckingEnabled);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CisaExceptions ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_hpcomuActionPerformed

    private void BroJordiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroJordiActionPerformed
       BroJordi f = null;
        try {
            f = new BroJordi(this, rootPaneCheckingEnabled);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_BroJordiActionPerformed

    private void BroLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroLCActionPerformed
        LC f = null;
        try {
            f = new LC(this, rootPaneCheckingEnabled);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_BroLCActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BroJordi;
    private javax.swing.JButton BroLC;
    private javax.swing.JButton hpcomu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
